apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lapilli.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "lapilli.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  # e.g. eks.amazonaws.com/role-arn (IRSA) or iam.gke.io/gcp-service-account (GKE WI).
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
